debug: false
m_name: "full"
camera_name: top_down_camera
tt_finetune: true
normalize: false
use_reward_model: false
action_repeat: 1
mode: pick-and-place-uv
uv_sample_method: bounding_box
gpu_num: 1
pointcloud: true
pc_voxel_size: 0.0216
add_occluded_particles: false
add_occluded_reward: false
seed: 100
delta_y: null
delta_y_range:
- 0
- 0.5
move_distance: null
policy: vcd
env_name: AnyClothFlatten
use_pred_rwd: false
is_train: false
slow_move: true
planning_method: random_shooting
use_pull_up: false
collect_data: false
dataf: ./datasets/0515-collect-cem-plan-no-pull-up-data/
sample_space: mesh
pick_vis_only: true
pred_mode: oneshot
model_path:
  Trousers: data/train/0112-noise-flowTrousers_v2/None
pred_time_interval: 5
full_dyn_path: data/train/trousers_gnn_old/1119-trousers-5000-full_1/full_dyn_75.pth
finetune: true
opt_model: false
opt_mesh_density: dense
opt_mesh_init: task
opt_lr: 0.001
opt_iter_total: 100
chamfer3d_w: 1.0
laplacian_w: 0.0
normal_w: 0.0
edge_w: 0.0
depth_w: 0
silhouette_w: 0
obs_consist_w: 10.0
consist_iter: 50
table_w: 10
reward_mode: full
reload_path: null
cloth_type: Trousers
pick_and_place_num: 1
ambiguity_agnostic: true
task: flatten
canon_model: sim
pos_mode: medor
mesh_mode: mc
radius_s: 0.005
radius_r: 0.01
# num_sample: 0
basepath: /home/zixuanhu/occlusion_reasoning/
test_episodes:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
use_wandb: false
move_distance_range:
- 0.05
- 0.2
pull_step: 10
wait_step: 6
cached_states_path: Trousers_hard_v4.pkl
mc_thres: 0.1
cem_num_pick: 500
num_worker: 4
_hidden_keys: []
chester_first_variant: true
exp_prefix: test
